source : contents
destination : publish

markdown_ext : "markdown,mkdown,mkdn,mkd,md"

markdown :    kramdown
highlighter : pygments
lsi :         false
excerpt_separator : "\n\n"

kramdown :
  input : GFM

baseurl : "/dev.koreahtml5.kr"